### ISSUE TITLE
Heure en format anglais

### ISSUE THREAD

**Issue by Travis-Le-Duc** [cglacet/attestations#2]
Salut, super repo.

En testant par curiosité, j'ai remarqué que l'heure donnée dans un scan du QR code est parfois en format anglais.

Ça peut être embêtant lors d'un controle...

A part ça, super app!
Merci de ton partage.

**Comment by Travis-Le-Duc** [comment]
Ah oui aussi, lorsque l’heure est en format anglais, il y a un décalage d’une heure en moins...

**Comment by cglacet** [comment]
Salut ! 

> En testant par curiosité, j'ai remarqué que l'heure donnée dans un scan du QR code est parfois en format anglais.

C'est le cas chez moi quand je génère sur le [portail officiel](https://media.interieur.gouv.fr/deplacement-covid-19/), donc j'imagine que c'est le format attendu par quiconque utilisera le QR code (une application qui doit également utiliser le format anglais)

D'ailleurs j'ai corrigé ce matin un bug dans ma version et je constate qu'il y est dans la version ofcielle (la date apparait au format anglais dans le PDF).

> Ah oui aussi, lorsque l’heure est en format anglais, il y a un décalage d’une heure en moins...

Ah, c'est possible, je regarderai dès que possible 👍

**Comment by cglacet** [comment]
D'ailleurs je vois que dans le QR code l'heure est sur un fuseau horaire étrange (exemple de celle générée juste avant 21h, dans le QR code on a Sortie: 02/11/2020 a 22:59;)

**Comment by Travis-Le-Duc** [comment]
> C'est le cas chez moi quand je génère sur le portail officiel, donc j'imagine que c'est le format attendu par quiconque utilisera le QR code (une application qui doit également utiliser le format anglais)
D'ailleurs j'ai corrigé ce matin un bug dans ma version et je constate qu'il y est dans la version ofcielle (la date apparait au format anglais dans le PDF).

Ah bizarre... Après vérification, le portail officiel me donne bien une heure (dans le QR code) et une date (dans le PDF) en format français... 

Peut être que cette histoire de format vient de la configuration du navigateur de chacun?

**Comment by cglacet** [comment]
> Peut être que cette histoire de format de l'heure vient de la configuration du téléphone de chacun?

C'est une très bonne question, je pense que non normalement. Comme j'utilise le code source officiel pour la génération de PDF (et donc du QR code) je n'ai pas trop regardé ce qui se passe en détail, mais ça reste assez simple donc on pourra tirer cette histoire au clair. Peut être que le type de donné attendu pour la date n'est pas le bon, maintenant moi je lui passe une chaine de caractères que je construit [comme ça](https://github.com/cglacet/attestations/blob/41bcb7192c53a1c8e12ec602afedf55c8b431ac0/src/config.js#L76-L86), en gros : 

```js
function frenchDate(date, langCode) {
    var day = date.toLocaleString(langCode, {day: '2-digit'});
    var month = date.toLocaleString(langCode, {month: '2-digit'});
    var year = date.toLocaleString(langCode, {year: 'numeric'});
    return `${day}/${month}/${year}`;
}

const date = new Date();
const dateData = {
        'heuresortie': date.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit', timeZone: "Europe/Paris", hour12: false }),
        'datesortie': frenchDate(date, 'fr-FR')
}
dateData;
```

Pour ceux (sur chrome) qui veulent essayer rapidement, vous pouvez juste ouvrir une console (sur mac `Command+Option+J`,  sur linux/windows `Control+Shift+J`) et copier coller le code ci-dessus. Chez moi (3 nov. 14h36 heure locale) ça donne : 

```js
{heuresortie: "14:36", datesortie: "03/11/2020"}
```

J'ai du mettre la `timeZone` explicitement car le serveur Heroku n'est visiblement pas sur celle de Paris. L'intégralité du code exécuté est sur Heroku (je n'appelle pas une API officielle, car j'utilise leur code source directement). Donc si il y a un problème je peux le régler sans attendre une modification sur la version officielle.

**Comment by cglacet** [comment]
Ceci dit, sur le portail officiel le PDF est généré par le client et donc effectivement les dates et heures dependent de la configuration de l'appareil utilisé. (je me rends compte que j'avais mal compris la question). 

Dans mon cas je peux forcer un format comme je génère le PDF coté serveur. Reste à trouver le problème bien sûr 🤔

**Comment by cglacet** [comment]
Alors, j'ai lu le code de la version officielle et le QR code contient [les informations suivantes](https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/40fe1abbaf679df06d88f53a58a5f739ca5c4fd0/src/js/pdf-util.js#L35-L43) :

```js
  const data = [
    `Cree le: ${creationDate} a ${creationHour}`,
    `Nom: ${lastname}`,
    `Prenom: ${firstname}`,
    `Naissance: ${birthday} a ${placeofbirth}`,
    `Adresse: ${address} ${zipcode} ${city}`,
    `Sortie: ${datesortie} a ${heuresortie}`,
    `Motifs: ${reasons}`,
  ].join(';\n ')
```

Sachant que la date est générée [ainsi](https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/blob/40fe1abbaf679df06d88f53a58a5f739ca5c4fd0/src/js/form-util.js#L75-L76) : 

```js
const dateSortie = field.value.split('-')
value = `${dateSortie[2]}/${dateSortie[1]}/${dateSortie[0]}`;
```

Le `field.value` provient d'un `input` de type `date`, à noter la remarque de [la doc](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Value) :

> **The displayed date format will differ from the actual `value`** — the displayed date is formatted based on the locale of the user's browser, but the parsed `value` is always formatted `yyyy-mm-dd`.

Donc après split puis concaténation, on a normalement `dd/mm/yyyy`.
Ce qui veut dire qu'il est étrange qu'on ai vu des bugs. Je me demande ce qui a bien pu se passer.

De mon coté je donne la date en chaine de caractères directement au générateur de QR code donc normalement aucun risque, mais j'ai peut être écrit une bêtise quelque part.

**Comment by Travis-Le-Duc** [comment]
Ah d'accord, la génération de la date est exécuté coté serveur, je comprends mieux.

En effet, tu as bien défini la timezone avec le bon format, c'est bizarre...

Par contre j'ai trouvé [ça](https://prashantsuthar.com/set-default-timezone-in-nodejs/) qui est peut être intéressant pour ici, un moyen de définir la timezone par défaut dans le serveur. Mais bon ça ne permettrait pas de savoir d’où vient le problème de format sur la date.

**Comment by Travis-Le-Duc** [comment]
Ah mais oui, en fait, tu définis la timzone et le format dans le code de génération de PDF, mais pas dans le code de génération QR code. Comme c’est exécuté aussi côté serveur, tu dois aussi définir ces paramètres.

Prendre les mêmes paramètres que ceux là:

```javaScript
const dateData = {
        'heuresortie': date.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit', timeZone: "Europe/Paris", hour12: false }),
        'datesortie': frenchDate(date, 'fr-FR')
}
```

Et les mettre dans ce code:
```javaScript
const creationHour = creationInstant
.toLocaleTimeString('fr-FR', { hour: '2-digit', minute: '2-digit' })
.replace(':', 'h')
```

**Comment by cglacet** [comment]
Ahhhh !!! Ok, j'avais pas fait attention, je n'avais pas vu qu'il y avait 2 champs pour les dates et heures (creation vs. sortie). Ce bout de code vient directement du dépot officiel, ce qui explique que l'heure dans le QR code sur la version officielle dépende de la configuration locale. 

Et dans mon cas effectivement il faut que je modifie cette partie du code.

Merci !

**Comment by cglacet** [comment]
J'ai craqué, javascript est vraiment trop aléatoire avec les dates. J'ai utilisé [moment-timezone](https://momentjs.com/timezone/) en espérant que ça soit plus stable.
