### ISSUE TITLE
Retirer le multi select pour les reasons

### ISSUE THREAD

**Issue by inicolas69** [cglacet/attestations#4]
Bonjour, je voulais soumettre une petite PR, mais malheureusement je n'ai pas les droits, pour retirer le multi select des reasons, qui n'a pas vraiment lieu d'être étant donné que l'on doit sélectionner une seule raison par attestation.

**Comment by cglacet** [comment]
Bonjour, comme la version officielle permet de cocher plusieurs cases j'ai laissé comme ça. Est-ce certain qu'on est censé n'en cocher qu'une ? (J'avoue que je trouve ça plus logique aussi, j'ai été surpris en y regardant de plus près.)

**Comment by inicolas69** [comment]
Le pdf lui même indique `certifie que mon déplacement est lié au motif suivant (cocher la case) autorisé par le décret n°2020-1310` , donc pour moi, un seul motif doit être coché.
J'avoue ne pas avoir fait attention au fait que c'était aussi comme ca sur la version officielle.

**Comment by cglacet** [comment]
Moi je suis chaud pour l'enlever le multiselect, je trouve ça plus logique donc si je ne suis pas seul je l'enlève 👍

**Comment by cglacet** [comment]
D'ailleurs maintenant je serais curieux de savoir pourquoi les PR ne sont pas autorisé pour quiconque par défaut sur github.

**Comment by cglacet** [comment]
A priori par défaut n'importe qui peut soumettre une nouvelle PR, ceci dit je ne trouve pas l'option, même en cherchant sur google.
