### ISSUE TITLE
Heure de création

### ISSUE THREAD

**Issue by ghost** [cglacet/attestations#5]
Bonjour,

Lorsque l’on scan le QR code de l’attestation générée. L’heure de création est erroné (-1h) peut-être à cause du changement d’heure ?

Merci en tous cas 🤘

**Comment by cglacet** [comment]
Bonjour, 

C'est peut être dû à [ce bug](https://github.com/cglacet/attestations/issues/2) ? Tu as l'heure dans quel format exactement ? 

Merci à toi aussi :)

**Comment by cglacet** [comment]
Si tu peux ré-essayer maintenant aussi, je viens juste de push la nouvelle version sur Heroku.

**Comment by ghost** [comment]
Effectivement 👍
Vive JS ...

**Comment by cglacet** [comment]
Dans ce cas précis c'était clairement ma faute ^^
