### ISSUE TITLE
RGPD

### ISSUE THREAD

**Issue by jmleroux** [cglacet/attestations#6]
Bonjour,

J'avais moi-même codé une alternative à base de queryString et je l'ai arrêtée assez vite car je ne suis pas sûr que ce soit valide en face de la RGPD. En effet, même si l'appli ne stocke aucune info, ces informations personnelles peuvent peut-être se retrouver dans les logs serveur. A vérifier pour ne pas risquer un problème de conformité :wink: 

Cordialement,
JM Leroux

**Comment by cglacet** [comment]
Bonjour, 

Effectivement, très bonne remarque je n'avais pas pensé à ça. J'ai l'impression qu'on ne peut pas supprimer les logs (router) d'Heroku. En tout cas c'est ce que j'ai pu voir sur un [vague post perdu sur stackoverflow](https://stackoverflow.com/a/22582696/1720199). 

Ceci dit les logs sont très limités ([1500 lignes, 1 semaine maximum](https://devcenter.heroku.com/articles/logging#log-history-limits)) et j'imagine que dans cette limite là c'est ok par rapport à la RGPD ? Surtout dans ce cas où on ne parle pas de données trop sensibles.

> ## Log history limits
> Logplex is designed for collating and routing log messages, not for storage. It retains the most recent 1,500 lines of your > consolidated logs, which expire after 1 week.

Dans l'idéal [j'aimerai](https://github.com/cglacet/attestations#todo) générer un maximum de chose coté client, si j'ai le temps je bosserai sur ça en premier :).

**Comment by jmleroux** [comment]
> Surtout dans ce cas où on ne parle pas de données trop sensibles.

Nom, adresse date de naissance. Des données que des experts du géo marketing adorent :wink: 

Je ne sais pas vraiment ce qui est sensible, mais personnellement je ne voulais pas être responsable d'une quelconque collecte de données et c'est pour cela que j'ai fermé l'url publique de mon appli avec purge complète de tout le système et que je la limite désormais à des connaissances averties.

**Comment by jmleroux** [comment]
Et je ferme cette issue qui n'avait pour but que de vous signaler ce possible souci.

**Comment by jmleroux** [comment]
Pour gérer ces infos du côté client, il y a une PR sur le repo officiel qui est intéressante: https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020/pull/50
